<?php
use NumericDataTypes\DataType\Duration;
use NumericDataTypes\DataType\Timestamp;
use NumericDataTypes\Form\Element\Timestamp as TimestampElement;
use NumericDataTypes\Form\Element\Interval as IntervalElement;
use NumericDataTypes\Form\Element\Duration as DurationElement;
use NumericDataTypes\Form\Element\Integer as IntegerElement;

$this->headScript()->appendFile($this->assetUrl('js/numeric-data-types.js', 'NumericDataTypes'));
$this->headLink()->appendStylesheet($this->assetUrl('css/numeric-data-types.css', 'NumericDataTypes'));
?>

<div class="field" id="numeric-timestamp-after">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Date comes after'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[ts][gt][pid]',
            'attributes' => [
                'id' => 'timestamp-after-pid',
                'class' => 'chosen-select',
                'value' => isset($query['numeric']['ts']['gt']['pid']) ? $query['numeric']['ts']['gt']['pid'] : null,
            ],
            'options' => [
                'numeric_data_type' => 'timestamp',
            ],
        ]);
        $element = new TimestampElement('numeric[ts][gt][val]');
        $element->setValue(isset($query['numeric']['ts']['gt']['val']) ? $query['numeric']['ts']['gt']['val'] : null);
        echo $this->formElement($element);
        ?>
    </div>
</div>

<div class="field" id="numeric-timestamp-before">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Date comes before'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[ts][lt][pid]',
            'attributes' => [
                'id' => 'timestamp-before-pid',
                'class' => 'chosen-select',
                'value' => isset($query['numeric']['ts']['lt']['pid']) ? $query['numeric']['ts']['lt']['pid'] : null,
            ],
            'options' => [
                'numeric_data_type' => 'timestamp',
            ],
        ]);
        $element = new TimestampElement('numeric[ts][lt][val]');
        $element->setValue(isset($query['numeric']['ts']['lt']['val']) ? $query['numeric']['ts']['lt']['val'] : null);
        echo $this->formElement($element);
        ?>
    </div>
</div>

<div class="field" id="numeric-duration-gt">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Duration is greater than'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[dur][gt][pid]',
            'attributes' => [
                'class' => 'chosen-select',
                'value' => isset($query['numeric']['dur']['gt']['pid']) ? $query['numeric']['dur']['gt']['pid'] : null,
            ],
            'options' => [
                'numeric_data_type' => 'duration',
            ],
        ]);
        $element = new DurationElement('numeric[dur][gt][val]');
        $element->setValue(isset($query['numeric']['dur']['gt']['val']) ? $query['numeric']['dur']['gt']['val'] : null);
        echo $this->formElement($element);
        ?>
    </div>
</div>

<div class="field" id="numeric-duration-lt">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Duration is less than'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[dur][lt][pid]',
            'attributes' => [
                'class' => 'chosen-select',
                'value' => isset($query['numeric']['dur']['lt']['pid']) ? $query['numeric']['dur']['lt']['pid'] : null,
            ],
            'options' => [
                'numeric_data_type' => 'duration',
            ],
        ]);
        $element = new DurationElement('numeric[dur][lt][val]');
        $element->setValue(isset($query['numeric']['dur']['lt']['val']) ? $query['numeric']['dur']['lt']['val'] : null);
        echo $this->formElement($element);
        ?>
    </div>
</div>

<div class="field" id="numeric-interval">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Date in interval'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[ivl][pid]',
            'attributes' => [
                'id' => 'interval-pid',
                'class' => 'chosen-select',
                'value' => isset($query['numeric']['ivl']['pid']) ? $query['numeric']['ivl']['pid'] : null,
            ],
            'options' => [
                'numeric_data_type' => 'interval',
            ],
        ]);
        $element = new TimestampElement('numeric[ivl][val]');
        $element->setValue(isset($query['numeric']['ivl']['val']) ? $query['numeric']['ivl']['val'] : null);
        echo $this->formElement($element);
        ?>
    </div>
</div>

<div class="field">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Value is greater than'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[int][gt][pid]',
            'attributes' => [
                'class' => 'chosen-select',
                'value' => isset($query['numeric']['int']['gt']['pid']) ? $query['numeric']['int']['gt']['pid'] : null,
            ],
            'options' => [
                'numeric_data_type' => 'integer',
            ],
        ]);
        $element = new IntegerElement('numeric[int][gt][val]');
        $element->setValue(isset($query['numeric']['int']['gt']['val']) ? $query['numeric']['int']['gt']['val'] : null);
        echo $this->formElement($element);
        ?>
    </div>
</div>

<div class="field">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Value is less than'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[int][lt][pid]',
            'attributes' => [
                'class' => 'chosen-select',
                'value' => isset($query['numeric']['int']['lt']['pid']) ? $query['numeric']['int']['lt']['pid'] : null,
            ],
            'options' => [
                'numeric_data_type' => 'integer',
            ],
        ]);
        $element = new IntegerElement('numeric[int][lt][val]');
        $element->setValue(isset($query['numeric']['int']['lt']['val']) ? $query['numeric']['int']['lt']['val'] : null);
        echo $this->formElement($element);
        ?>
    </div>
</div>
