<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/numeric-data-types.css', 'NumericDataTypes'));
$this->headScript()->appendFile($this->assetUrl('js/numeric-data-types.js', 'NumericDataTypes'));
$formText = clone($this->plugin('formText'));
$formText->addTranslatableAttribute('aria-label');
?>
<div class="numeric-integer">
    <div class="error invalid-value"
        data-invalid-message="<?php echo $this->escapeHtml($this->translate('Invalid value: %s')); ?>"
        data-custom-validity="<?php echo $this->escapeHtml($this->translate('Value must be a integer or decimal; the number digits to the left and right of a decimal cannot exceed 16')); ?>">
    </div>
    <?php echo $this->formHidden($element->getValueElement()); ?>
    <div class="numeric-integer-inputs">
        <?php echo $formText($element->getIntegerElement()); ?>
    </div>
</div>
