<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/numeric-data-types.css', 'NumericDataTypes'));
if ($this->status()->isAdminRequest()) {
    $this->headLink()->appendStylesheet($this->assetUrl('css/numeric-data-types-admin.css', 'NumericDataTypes'));
}
$this->headScript()->appendFile($this->assetUrl('js/numeric-data-types.js', 'NumericDataTypes'));
$formNumber = clone($this->plugin('formNumber'));
$formNumber->addTranslatableAttribute('aria-label');
$formSelect = clone($this->plugin('formSelect'));
$formSelect->addTranslatableAttribute('aria-label');
?>
<div class="numeric-date-inputs">
    <label>
        <?php echo $this->translate('Year'); ?>
        <?php echo $formNumber($element->getYearElement()); ?>
    </label>
    <label>
        <?php echo $this->translate('Month'); ?>
        <?php echo $formSelect($element->getMonthElement()); ?>
    </label>
    <label>
        <?php echo $this->translate('Day'); ?>
        <?php echo $formSelect($element->getDayElement()); ?>
    </label>
    <label class="numeric-toggle-time button" title="<?php echo $this->translate('Time'); ?>"><input type="checkbox" class="numeric-toggle-time-checkbox" name="numeric-toggle-time-checkbox" aria-label="<?php echo $this->translate('Time'); ?>"></label>
</div>
<div class="numeric-time-inputs">
    <label>
        <?php echo $this->translate('Hour'); ?>
        <?php echo $formSelect($element->getHourElement()); ?>
    </label>
    <label>
        <?php echo $this->translate('Minute'); ?>
        <?php echo $formSelect($element->getMinuteElement()); ?>
    </label>
        <label>
        <?php echo $this->translate('Second'); ?>
        <?php echo $formSelect($element->getSecondElement()); ?>
    </label>
</div>
<div class="error invalid-value"
data-custom-validity="<?php echo $this->escapeHtml($this->translate('Value must be a datetime')); ?>"></div>
<?php echo $this->formHidden($element->getValueElement()); ?>
