<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/numeric-data-types.css', 'NumericDataTypes'));
$this->headScript()->appendFile($this->assetUrl('js/numeric-data-types.js', 'NumericDataTypes'));
$formNumber = clone($this->plugin('formNumber'));
$formNumber->addTranslatableAttribute('aria-label');
?>
<div class="numeric-duration">
    <div class="numeric-datetime-inputs">
        <div class="numeric-date-inputs">
            <label>
                <?php echo $this->translate('Years'); ?>
                <?php echo $formNumber($element->getYearsElement()); ?>
            </label>
            <label>
                <?php echo $this->translate('Months'); ?>
                <?php echo $formNumber($element->getMonthsElement()); ?>
            </label>
            <label>
                <?php echo $this->translate('Days'); ?>
                <?php echo $formNumber($element->getDaysElement()); ?>
            </label>
            <label class="numeric-toggle-time button" title="<?php echo $this->translate('Time'); ?>"><input type="checkbox" name="numeric-toggle-time-checkbox" aria-label="<?php echo $this->translate('Time'); ?>"></label>
        </div>
        <div class="numeric-time-inputs">
            <label>
                <?php echo $this->translate('Hours'); ?>
                <?php echo $formNumber($element->getHoursElement()); ?>
            </label>
            <label>
                <?php echo $this->translate('Minutes'); ?>
                <?php echo $formNumber($element->getMinutesElement()); ?>
            </label>
            <label>
                <?php echo $this->translate('Seconds'); ?>
                <?php echo $formNumber($element->getSecondsElement()); ?>
            </label>
        </div>
    </div>
    <div class="error invalid-value"
        data-invalid-message="<?php echo $this->escapeHtml($this->translate('Invalid value: %s')); ?>"
        data-custom-validity="<?php echo $this->escapeHtml($this->translate('Value must be a duration')); ?>"></div>
    <?php echo $this->formHidden($element->getValueElement()); ?>
</div>

