<?php
use NumericDataTypes\DataType\Timestamp;

$this->headScript()->appendFile($this->assetUrl('js/numeric-data-types.js', 'NumericDataTypes'));
$this->headLink()->appendStylesheet($this->assetUrl('css/numeric-data-types.css', 'NumericDataTypes'));

// Set default values.
$ltTimestamp = [
    'pid' => isset($query['numeric']['ts']['lt']['pid']) ? $query['numeric']['ts']['lt']['pid'] : null,
    'val' => isset($query['numeric']['ts']['lt']['val']) ? $query['numeric']['ts']['lt']['val'] : null,
    'year' => null,
    'month' =>  null,
    'day' => null,
    'hour' => null,
    'minute' => null,
    'second' => null,
];
$gtTimestamp = [
    'pid' => isset($query['numeric']['ts']['gt']['pid']) ? $query['numeric']['ts']['gt']['pid'] : null,
    'val' => isset($query['numeric']['ts']['gt']['val']) ? $query['numeric']['ts']['gt']['val'] : null,
    'year' => null,
    'month' =>  null,
    'day' => null,
    'hour' => null,
    'minute' => null,
    'second' => null,
];
$ltInteger = [
    'pid' => isset($query['numeric']['int']['lt']['pid']) ? $query['numeric']['int']['lt']['pid'] : null,
    'val' => isset($query['numeric']['int']['lt']['val']) ? $query['numeric']['int']['lt']['val'] : null,
];
$gtInteger = [
    'pid' => isset($query['numeric']['int']['gt']['pid']) ? $query['numeric']['int']['gt']['pid'] : null,
    'val' => isset($query['numeric']['int']['gt']['val']) ? $query['numeric']['int']['gt']['val'] : null,
];

// Prepare passed values.
if (isset($ltTimestamp['val'])) {
    $date = Timestamp::getDateTimeFromValue($ltTimestamp['val']);
    $ltTimestamp['year'] = $date['year'];
    $ltTimestamp['month'] = $date['month'];
    $ltTimestamp['day'] = $date['day'];
    $ltTimestamp['hour'] = $date['hour'];
    $ltTimestamp['minute'] = $date['minute'];
    $ltTimestamp['second'] = $date['second'];
}
if (isset($gtTimestamp['val'])) {
    $date = Timestamp::getDateTimeFromValue($gtTimestamp['val']);
    $gtTimestamp['year'] = $date['year'];
    $gtTimestamp['month'] = $date['month'];
    $gtTimestamp['day'] = $date['day'];
    $gtTimestamp['hour'] = $date['hour'];
    $gtTimestamp['minute'] = $date['minute'];
    $gtTimestamp['second'] = $date['second'];
}

$months = [
    1 => $this->translate('January'),
    2 => $this->translate('February'),
    3 => $this->translate('March'),
    4 => $this->translate('April'),
    5 => $this->translate('May'),
    6 => $this->translate('June'),
    7 => $this->translate('July'),
    8 => $this->translate('August'),
    9 => $this->translate('September'),
    10 => $this->translate('October'),
    11 => $this->translate('November'),
    12 => $this->translate('December'),
];
?>

<div class="field">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Date comes before'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[ts][lt][pid]',
            'attributes' => [
                'id' => 'timestamp-before-pid',
                'class' => 'chosen-select',
                'value' => $ltTimestamp['pid'],
            ],
            'options' => [
                'numeric_data_type' => 'timestamp',
            ],
        ]);
        ?>
        <div class="timestamp-datetime-inputs">
            <div class="timestamp-date-inputs">
                <input type="number" value="<?php echo $this->escapeHtml($ltTimestamp['year']); ?>" id="timestamp-before-year" step="1" min="<?php echo Timestamp::YEAR_MIN; ?>" max="<?php echo Timestamp::YEAR_MAX; ?>" placeholder="<?php echo $this->translate('Year'); ?>">
                <select id="timestamp-before-month">
                    <option value=""><?php echo $this->translate('Month'); ?></option>
                    <?php foreach ($months as $index => $month): ?>
                    <option value="<?php echo $index; ?>"<?php echo ($index == $ltTimestamp['month']) ? ' selected' : null; ?>><?php echo $month; ?></option>
                    <?php endforeach; ?>
                </select>
                <input type="number" value="<?php echo $this->escapeHtml($ltTimestamp['day']); ?>" id="timestamp-before-day" step="1" min="1" max="31" placeholder="<?php echo $this->translate('Day'); ?>">
                <a href="#" class="timestamp-toggle-time"><?php echo $this->translate('time'); ?></a>
            </div>
            <div class="timestamp-time-inputs">
                <input type="number" value="<?php echo $this->escapeHtml($ltTimestamp['hour']); ?>" id="timestamp-before-hour" step="1" min="0" max="59" placeholder="<?php echo $this->translate('Hour'); ?>">
                <input type="number" value="<?php echo $this->escapeHtml($ltTimestamp['minute']); ?>" id="timestamp-before-minute" step="1" min="0" max="59" placeholder="<?php echo $this->translate('Minute'); ?>">
                <input type="number" value="<?php echo $this->escapeHtml($ltTimestamp['second']); ?>" id="timestamp-before-second" step="1" min="0" max="59" placeholder="<?php echo $this->translate('Second'); ?>">
            </div>
        </div>
        <input type="hidden" id="timestamp-before-ts" name="numeric[ts][lt][val]">
    </div>
</div>

<div class="field">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Date comes after'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[ts][gt][pid]',
            'attributes' => [
                'id' => 'timestamp-after-pid',
                'class' => 'chosen-select',
                'value' => $gtTimestamp['pid'],
            ],
            'options' => [
                'numeric_data_type' => 'timestamp',
            ],
        ]);
        ?>
        <div class="timestamp-datetime-inputs">
            <div class="timestamp-date-inputs">
                <input type="number" value="<?php echo $this->escapeHtml($gtTimestamp['year']); ?>" id="timestamp-after-year" step="1" min="<?php echo Timestamp::YEAR_MIN; ?>" max="<?php echo Timestamp::YEAR_MAX; ?>" placeholder="<?php echo $this->translate('Year'); ?>">
                <select id="timestamp-after-month">
                    <option value=""><?php echo $this->translate('Month'); ?></option>
                    <?php foreach ($months as $index => $month): ?>
                    <option value="<?php echo $index; ?>"<?php echo ($index == $gtTimestamp['month']) ? ' selected' : null; ?>><?php echo $month; ?></option>
                    <?php endforeach; ?>
                </select>
                <input type="number" value="<?php echo $this->escapeHtml($gtTimestamp['day']); ?>" id="timestamp-after-day" step="1" min="1" max="31" placeholder="<?php echo $this->translate('Day'); ?>">
                <a href="#" class="timestamp-toggle-time"><?php echo $this->translate('time'); ?></a>
            </div>
            <div class="timestamp-time-inputs">
                <input type="number" value="<?php echo $this->escapeHtml($gtTimestamp['hour']); ?>" id="timestamp-after-hour" step="1" min="0" max="59" placeholder="<?php echo $this->translate('Hour'); ?>">
                <input type="number" value="<?php echo $this->escapeHtml($gtTimestamp['minute']); ?>" id="timestamp-after-minute" step="1" min="0" max="59" placeholder="<?php echo $this->translate('Minute'); ?>">
                <input type="number" value="<?php echo $this->escapeHtml($gtTimestamp['second']); ?>" id="timestamp-after-second" step="1" min="0" max="59" placeholder="<?php echo $this->translate('Second'); ?>">
            </div>
        </div>
        <input type="hidden" id="timestamp-after-ts" name="numeric[ts][gt][val]">
    </div>
</div>

<div class="field">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Value is less than'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[int][lt][pid]',
            'attributes' => [
                'class' => 'chosen-select',
                'value' => $ltInteger['pid'],
            ],
            'options' => [
                'numeric_data_type' => 'integer',
            ],
        ]);
        ?>
        <input type="number" value="<?php echo $this->escapeHtml($ltInteger['val']); ?>" step="1" name="numeric[int][lt][val]" placeholder="<?php echo $this->translate('Enter integer'); ?>">    </div>
</div>

<div class="field">
    <div class="field-meta">
        <label for=""><?php echo $this->translate('Value is greater than'); ?></label>
    </div>
    <div class="inputs">
        <?php
        echo $this->numericPropertySelect([
            'name' => 'numeric[int][gt][pid]',
            'attributes' => [
                'class' => 'chosen-select',
                'value' => $gtInteger['pid'],
            ],
            'options' => [
                'numeric_data_type' => 'integer',
            ],
        ]);
        ?>
        <input type="number" value="<?php echo $this->escapeHtml($gtInteger['val']); ?>" step="1" name="numeric[int][gt][val]" placeholder="<?php echo $this->translate('Enter integer'); ?>">    </div>
</div>

<script>
$(function() {
    $(document).find('#timestamp-after-hour, #timestamp-before-hour').each(function() {
        // By default, show time inputs only if there's an hour.
        var h = $(this);
        var timeInputs = h.closest('.timestamp-time-inputs');
        h.val() ? timeInputs.show() : timeInputs.hide();
    });

    $('form#advanced-search').on('submit', function (e) {
        var before = $('#timestamp-before-ts');
        var after = $('#timestamp-after-ts');
        NumericDataTypes.setDateValue(
            before,
            $('#timestamp-before-year'),
            $('#timestamp-before-month'),
            $('#timestamp-before-day'),
            $('#timestamp-before-hour'),
            $('#timestamp-before-minute'),
            $('#timestamp-before-second')
        );
        NumericDataTypes.setDateValue(
            after,
            $('#timestamp-after-year'),
            $('#timestamp-after-month'),
            $('#timestamp-after-day'),
            $('#timestamp-after-hour'),
            $('#timestamp-after-minute'),
            $('#timestamp-after-second')
        );
        if ('' === before.val()) {
            before.prop('disabled', true);
        }
        if ('' === after.val()) {
            after.prop('disabled', true);
        }
    });
});
</script>
