<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/numeric-data-types.css','NumericDataTypes'));
$this->headScript()->appendFile($this->assetUrl('js/numeric-data-types.js', 'NumericDataTypes'));
?>
<div class="numeric-timestamp">
    <?php echo $this->formHidden($element->getValueElement()); ?>
    <div class="numeric-datetime-inputs">
        <div class="numeric-date-inputs">
            <?php echo $this->formNumber($element->getYearElement()); ?>
            <?php echo $this->formSelect($element->getMonthElement()); ?>
            <?php echo $this->formSelect($element->getDayElement()); ?>
            <label class="numeric-toggle-time button" aria-title="<?php echo $this->translate('Time'); ?>" title="<?php echo $this->translate('Time'); ?>"><input type="checkbox" name="numeric-toggle-time-checkbox"/></label>
        </div>
        <div class="numeric-time-inputs">
            <?php echo $this->formSelect($element->getHourElement()); ?>
            <?php echo $this->formSelect($element->getMinuteElement()); ?>
            <?php echo $this->formSelect($element->getSecondElement()); ?>
        </div>
    </div>
</div>