<?php echo $this->formRow($elementPropertyId); ?>
<?php echo $this->formRow($elementValues); ?>
<p><input type="checkbox" id="date-after-show-timestamp-values"> <?php echo $this->translate('Show all available values of the selected property.'); ?></p>
<table id="date-after-timestamp-values" data-timestamp-values-url="<?php echo $this->escapeHtml($this->url('admin/site/slug/numeric-data-types-faceted-browse', ['controller' => 'index', 'action' => 'timestamp-values'], true)) ?>"></table>
